name: pepsico_loyalty
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  gettext: ^1.2.0
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.0
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  flutter_rating_bar: ^4.0.1
  dropdown_search: ^5.0.6
  shimmer: ^3.0.0
  quickalert: ^1.1.0
  extension: ^0.6.0


dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

